### ISSUE TITLE
利用已训练好的模型生成图片出错

### ISSUE THREAD

**Issue by chuxuezhi01** [hzy46/fast-neural-style-tensorflow#11]
执行代码后如下所示
lstreasure@lstreasure-OptiPlex-7040:~/下载/hzy46/fast-neural-style-tensorflow-master$ python eval.py --model_file models/wave.ckpt-done --image_file img/test.jpg
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
INFO:tensorflow:Image size: 712x474
Traceback (most recent call last):
  File "eval.py", line 62, in <module>
    tf.app.run()
  File "/home/lstreasure/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval.py", line 38, in main
    image = reader.get_image(FLAGS.image_file, height, width, image_preprocessing_fn)
  File "/home/lstreasure/下载/hzy46/fast-neural-style-tensorflow-master/reader.py", line 10, in get_image
    return preprocess_fn(image, height, width)
  File "/home/lstreasure/下载/hzy46/fast-neural-style-tensorflow-master/preprocessing/preprocessing_factory.py", line 70, in preprocessing_fn
    image, output_height, output_width, is_training=is_training, **kwargs)
  File "/home/lstreasure/下载/hzy46/fast-neural-style-tensorflow-master/preprocessing/vgg_preprocessing.py", line 388, in preprocess_image
    resize_side_min)
  File "/home/lstreasure/下载/hzy46/fast-neural-style-tensorflow-master/preprocessing/vgg_preprocessing.py", line 353, in preprocess_for_eval
    image = _central_crop([image], output_height, output_width)[0]
  File "/home/lstreasure/下载/hzy46/fast-neural-style-tensorflow-master/preprocessing/vgg_preprocessing.py", line 200, in _central_crop
    crop_height, crop_width))
  File "/home/lstreasure/下载/hzy46/fast-neural-style-tensorflow-master/preprocessing/vgg_preprocessing.py", line 76, in _crop
    tf.pack([crop_height, crop_width, original_shape[2]]))
AttributeError: 'module' object has no attribute 'pack'
请问什么原因，怎么解决，万分感谢帮忙的伙伴！

**Comment by chuxuezhi01** [comment]
请问有热心帮忙的小伙伴吗？急求帮助该问题

**Comment by leenkhan** [comment]
你tensorflow 是什么版本？
chuxuezhi01 <notifications@github.com>于2017年3月26日 周日16:36写道：

**Comment by chuxuezhi01** [comment]
你好，我的版本的是1.0.1

**Comment by chuxuezhi01** [comment]
@leenkhan 你好，我的tensorflow版本是1.0.1

**Comment by leenkhan** [comment]
原作者的代码不支持1.0及以上版本，只支持到0.12版本，你要改些地方才能运行，之前有follow 的作者修改支持到1.0，我follow
的版本跟着改了支持到1.0，你可以clone一个到你本地试试
chuxuezhi01 <notifications@github.com>于2017年3月26日 周日16:43写道：

**Comment by chuxuezhi01** [comment]
@leenkhan 哦哦，好的，我去试试你的，多谢你了

**Comment by leenkhan** [comment]
不用客气，我也是tensorflow菜鸟,大家相互帮助应该的
chuxuezhi01 <notifications@github.com>于2017年3月26日 周日16:51写道：

**Comment by chuxuezhi01** [comment]
@leenkhan 你好，我发邮件给你了，请抽时间帮帮我看看问题，多谢了

**Comment by hzy46** [comment]
@leenkhan @chuxuezhi01 
1、关于checkpoint读取出错

之前的代码是Tensorflow 0.11的，默认保存的checkpoint是Tensorflow V1格式。Tensorflow 更新到0.12后，就默认使用V2 格式的checkpoint，因此会出问题。commit 5309a2a 中已经注明write_version=tf.train.SaverDef.V1。更新到这个commit可以解决问题。

2、关于api出错

Tensorflow更新到1.0后大量api发生改变，我也做了新的调整。Tensorflow 1.0的用户请使用最新的commit，细节参考README.md。

谢谢支持！

--------------------------------
1、About Error on Reading Checkpoint

In Tensorflow 0.11, the default format for checkpoints is "V1". After Tensorflow 0.12, the default format becomes "V2". So it will be an error when reading V1 formatted checkpoint. In commit 5309a2a, I use "write_version=tf.train.SaverDef.V1" to address this problem.

2、About Error when calling Tensorflow API

After Tensorflow 1.0, many APIs have changed. Now I also changed the API to 1.0. Please see the latest commit and the latest README.md for details. 

Thank you for your support!
