### ISSUE TITLE
tensorflow貌似在python 2.7环境下无法下载

### ISSUE THREAD

**Issue by ohmyskyhigh** [hzy46/fast-neural-style-tensorflow#13]
用virtualenv装了python 2.7之后tensorflow就没法下了
我用的是
`pip install tensorflow`

>  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow

**Comment by hzy46** [comment]
纯粹tensorflow有关问题请自行解决哈~
