### ISSUE TITLE
使用训练好的模型出错

### ISSUE THREAD

**Issue by JiazeWang** [hzy46/fast-neural-style-tensorflow#14]
我使用的版本是 Python3.5 （Python2.7 似乎并不能支持 Tensorflow1.0啊） Tensorflow 1.0 ，在运行时报错
TypeError: Value passed to parameter 'paddings' has DataType float32 not in list of allowed values: int32, int64 。不知道有没有遇到同样问题的朋友，谢谢啦~

**Comment by hzy46** [comment]
我的环境下没有问题。

**Comment by JiazeWang** [comment]
@hzy46  学长好，请问你使用的环境是python3.5 嘛，我看说明上写的还是 python2.7.x？

**Comment by JiazeWang** [comment]
![1](https://cloud.githubusercontent.com/assets/22630087/24643269/804f22cc-193f-11e7-9fdf-5b4484c6f5ca.jpg)
问题如图所示

**Comment by JiazeWang** [comment]
该问题已经得到了解决，和我小组的同学在linux环境下使用python2.7 和tensorflow 1.0.1成功运行了作者的代码。而我在windows用python3.5的编译器是会报错的。所以和作者编译环境一致就可以了啊~ 感谢学长 @hzy46
