### ISSUE TITLE
运行python eval.py --model_file <your path to wave.ckpt-done> --image_file img/test.jpg 出来的图片是全黑的

### ISSUE THREAD

**Issue by zhaochenyang** [hzy46/fast-neural-style-tensorflow#16]
如题，是怎么回事？有遇到同样情况的吗？

**Comment by mosu027** [comment]
我遇到 了同样的情况，求解

**Comment by flyfj** [comment]
Looks like some weights in the trained model are nan. not sure why this would happen.

**Comment by shixpGit** [comment]
@hzy46 I got the same problem. 
Run the right command, and there is no error report, but the generated/res.jpg was black.
Is there any log file?

**Comment by hzy46** [comment]
@shixpGit Could you provide your python and tensorflow version?

**Comment by shixpGit** [comment]
@hzy46 
$python --version
Python 2.7.9
$python -c 'import tensorflow as tf; print(tf.__version__)'
1.1.0
:)

**Comment by hzy46** [comment]
Check the new commit from @LanKo-X
