### ISSUE TITLE
是否开启了gpu功能和多cpu功能

### ISSUE THREAD

**Issue by wangkepermit** [hzy46/fast-neural-style-tensorflow#20]
你好，不知道你这个项目有没有开启多cpu多线程以及gpu功能？如果有，默认的数值分别是多少？还有要如何进行自定义设置？非常感谢。

**Comment by hzy46** [comment]
支持gpu。cpu默认多线程。

**Comment by fakerName** [comment]
> 支持gpu。cpu默认多线程。

麻烦问一下如何开始GPU
