### ISSUE TITLE
ResourceExhaustedError

### ISSUE THREAD

**Issue by wangkepermit** [hzy46/fast-neural-style-tensorflow#21]
百度图片上随便下载一个图片，进行测试，报错如下
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,64,1578,2090]
	 [[Node: deconv2/conv_transpose/conv/conv = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](deconv2/conv_transpose/conv/MirrorPad, deconv2/conv_transpose/conv/weight/read)]]

**Comment by hzy46** [comment]
您机器内存或显存不足（图片可能过大）

**Comment by wangkepermit** [comment]
非常感谢你的回答！辛苦辛苦！
