### ISSUE TITLE
possible to train own images?

### ISSUE THREAD

**Issue by andyhx** [hzy46/fast-neural-style-tensorflow#23]
hi,I want to train my own datas, not coco images ,I  have got only one image set,their style  are all the same,
 Assume the style is A. Is it possible to put one content image to transfer it to A style

**Comment by hzy46** [comment]
Yes, it is possible. Modify the "train2014/" in train.py to your own image folder.

**Comment by jl1980** [comment]
train一张图片要多久时间啊？我昨天晚上在虚拟机的ubuntu里运行了一晚上，早上起来看还没结束。
