### ISSUE TITLE
New trained models are not beautiful

### ISSUE THREAD

**Issue by dryks** [hzy46/fast-neural-style-tensorflow#28]
New trained models are not beautiful

name:fast-style-model.ckpt-1000

vps 2core 7 gig ram cpu azure

Picture treated with a new model:
https://cs541600.userapi.com/c837722/v837722161/5048f/md044VZdNsI.jpg

**Comment by hzy46** [comment]
Suggestion: use GPU and continue training more steps..

**Comment by dryks** [comment]
How many steps are needed for normal quality?

**Comment by hzy46** [comment]
I run 2 epochs on MS COCO dataset. 

To caculate the step: step = epoch * image_num / batch_size
