### ISSUE TITLE
如果我要使用Inception_resnet_v2 或者其他模型, 我应该选择哪些层

### ISSUE THREAD

**Issue by wqj97** [hzy46/fast-neural-style-tensorflow#29]
VGG_16好理解, 但是如果我想用Inception_resnet_v2
或者是Inception_v4
我应该如何处理
style_layers
和
content_layers

**Comment by wqj97** [comment]
另外还有一个问题是, 有没有调
style_weight和content_weight, tv_weight的经验可以介绍下~

**Comment by hzy46** [comment]
需要定义一个image_unprocessing_fn 。其他的仿照写就可以了。

调参要多调才有感觉，先参考给定的参数吧。

**Comment by wqj97** [comment]
谢谢你的回答~
我想请问下, 用哪几层做style_layer和content_layer比较合适呢~

**Comment by hzy46** [comment]
看yaml设置
