### ISSUE TITLE
训练结果不是很满意，请问下是什么原因呢？

### ISSUE THREAD

**Issue by raymondmg** [hzy46/fast-neural-style-tensorflow#30]
训练结果不是很满意，请问下是什么原因呢？

yaml文件里面参数的问题吗，我是按照其他几个案例写的

下面是训练图片以及测试结果：

[http://img0.ph.126.net/dzpphGpFMD7NAJdBOwTzaw==/6632572997119370514.jpg](http://img0.ph.126.net/dzpphGpFMD7NAJdBOwTzaw==/6632572997119370514.jpg)

[http://img2.ph.126.net/rhl8G4PhbbrN8owjZph4SQ==/6632375085026365379.jpg](http://img2.ph.126.net/rhl8G4PhbbrN8owjZph4SQ==/6632375085026365379.jpg)

[http://img2.ph.126.net/EBTspU7jpLxvLBCz5Q5j7w==/6632530116165886301.jpg](http://img2.ph.126.net/EBTspU7jpLxvLBCz5Q5j7w==/6632530116165886301.jpg)

**Comment by hzy46** [comment]
图片太大了。把图片尺寸缩小就可以了

**Comment by raymondmg** [comment]
哪张图片太大了呢，风格图片在预处理的时候不是会放缩到conf中设定的数值上吗，这个数值我没修改的256应该是。

**Comment by hzy46** [comment]
![image](https://user-images.githubusercontent.com/7499023/28750029-abace57c-750f-11e7-97af-706b7af69d89.png)

这张图片尺寸较大，因此风格化表现在较小的尺度。你把它缩小。

**Comment by ShiYujin** [comment]
请问学习的图片要压缩到多大才比较合适？我用800*900的图片训练，结果在loss 300000左右震荡，step已经到了4000+，还在继续。

**Comment by hzy46** [comment]
没研究过这个问题

**Comment by neal668** [comment]
请问下新的模型一般要训练多少epoch？

**Comment by hzy46** [comment]
1~2

**Comment by wunengguang** [comment]
结果在loss 300000左右震荡，step已经到了8000+，还在继续。迁移的效果不是很好。而且感觉是出现了棋盘效应

**Comment by oneHuster** [comment]
请问图片256*256但是训练集数量不大，会导致loss震荡不下嘛？生成的图片效果很差，而且，regularizer loss一直在升高。

**Comment by XiangLuoyang** [comment]
@wunengguang 你好~我想请问一下，如果模型还没有训练完的话，可以用它看一下迁移的效果的吗？
