### ISSUE TITLE
关于vgg模型的迁移应用

### ISSUE THREAD

**Issue by BENZJ** [hzy46/fast-neural-style-tensorflow#45]
看过论文之后好像是说把训练好的模型拿来用是不是应该要把vgg中的模型里的参数都改为转变为常量呢？我感觉代码中似乎没有这个静态化的过程？不知道是我论文理解错了还是代码没有看懂的，能指导解答一下吗？

**Comment by hzy46** [comment]
不训练这部分参数 = 你说的静态化

**Comment by aigeek** [comment]
作者好，请问是否知道有什么办法把这个python的模型导出到android使用吗，有没有什么可用的参考资料可提供呢，谢谢！@hzy46
