### ISSUE TITLE
训练一个模型需要多少时间呢

### ISSUE THREAD

**Issue by czczup** [hzy46/fast-neural-style-tensorflow#51]
代码在我的python3.6上直接就可以运行了
有几个问题想请教一下：
按照原来yml里面的配置，训练一个模型需要迭代多少个批次？
loss大概下降到多少？
style_weight是凭感觉设置的吗？

**Comment by 14080204** [comment]
请问一下，作者说的python2.7.x运行，您的python3.6也可以运行是么？

**Comment by czczup** [comment]
嗯，直接就可以运行了，没有做修改





在 2018-04-30 19:41:32，"14080204" <notifications@github.com> 写道：


请问一下，作者说的python2.7.x运行，您的python3.6也可以运行是么？

**Comment by XiangLuoyang** [comment]
我也想问这个问题，在知乎上看到作者说迭代了40000次，也有人回复将iter_number改为5000或者2000也可以，因为后面几千次都是循环。我这里不明白最后的loss到了多少以及在哪里改这个iter_number

**Comment by GrayXu** [comment]
原文是在Torch上用Titan X训练了4小时

**Comment by iptop** [comment]
@GrayXu 一个纹理要4小时吗

**Comment by czczup** [comment]
Nvidia gtx965m 大概要训练8个小时，因为显存只有4G，所以batch_size设的2，epoch设的1
